k6 run graphqlAllParks.js
timeout /t 60
k6 run graphqlPartialParks.js
timeout /t 60
k6 run graphqlCreateUser.js
timeout /t 60
k6 run graphqlLeavePark.js
timeout /t 60
k6 run graphqlUpdateParkingValue.js