@startuml leavePark
User -> Mutation: Sends HTTP Mutation Request
Mutation -> ParkLogService: Stop Counting Time Operation
ParkLogService -> ParkLogService: Create Park Log
ParkLogService -> ParkLogMapper: Map to Domain
ParkLogService <- ParkLogMapper: Returns Result
ParkLogService -> ParkLogRepository: Create Park Log
Mutation -> PaymentService: Calculate Cost
Mutation <- PaymentService: Returns Cost
Mutation -> PaymentService: Make Payment
PaymentService -> PaymentService: Pay with Parky Coins
alt (totalCost - parkyCoinsSpent) > 0
    PaymentService -> PaymentService: Simulate Payment
    PaymentService -> PaymentServiceApplication: Send HTTP Mutation Request
    PaymentService <- PaymentServiceApplication: Returns Result
    PaymentService -> PaymentService: Returns Result
end
PaymentService -> InvoiceRepository: Create Invoice
PaymentService -> PaymentService: Creates Payment Summary
Mutation <- PaymentService: Returns Payment Summary
User <- Mutation: Returns Result
@enduml