@startuml updateParkingValue
User -> Mutation: Sends HTTP Mutation Request
Mutation -> ParkyWalletService: Update Parking Value
ParkyWalletService -> ParkyCoinsConfigurationRepository: Checks If Email Exists
ParkyWalletService <- ParkyCoinsConfigurationRepository: Returns Result
Mutation <- ParkyWalletService: Returns Result
User <- Mutation: Returns Result
@enduml